/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.Codes;

import com.ManageDetails.Student;
import com.database.DBconnect;
import static com.database.DBconnect.CONN;
import com.database.Sql;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.Arrays;
import java.util.Random;
import static com.Codes.Commons.date;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Dell
 */
public class Rubbish {

    public static void main(String[] args) throws IOException, SQLException {
        //<editor-fold defaultstate="collapsed" desc="Names">
        String[] names = {
            "Kasun",
            "Indika",
            "Gayan",
            "Nuwan",
            "Amila",
            "Chaminda",
            "Janaka",
            "Roshan",
            "Ruwan",
            "Sampath",
            "Dinesh",
            "Asanka",
            "Sameera",
            "Saman",
            "Pradeep",
            "Ajith",
            "Tharindu",
            "Sanjeewa",
            "Chandana",
            "Mahesh",
            "Lahiru",
            "Aruna",
            "Manjula",
            "Buddhika",
            "Isuru",
            "Sarath",
            "Fathima",
            "Prasanna",
            "Rasika",
            "Mohammed",
            "Priyantha",
            "Fernando",
            "Nishantha",
            "Harsha",
            "Nalin",
            "Thilina",
            "Upul",
            "Thushara",
            "Gamini",
            "Manoj",
            "Anura",
            "Dhanushka",
            "Thilini",
            "Chamara",
            "Ranjith",
            "Chanaka",
            "Abdul",
            "Samantha",
            "Chinthaka",
            "Rohan",
            "Sanjaya",
            "Lalith",
            "Chathura",
            "Wasantha",
            "Jagath",
            "Sunil",
            "Suranga",
            "Gihan",
            "Tharanga",
            "Prasad",
            "Chamila",
            "Suresh",
            "Jayantha",
            "Nimal",
            "Anuradha",
            "Ravi",
            "Hasitha",
            "Lasantha",
            "Supun",
            "Chandima",
            "Charith",
            "Kamal",
            "Kanchana",
            "Thusitha",
            "Prabath",
            "Duminda",
            "Nalaka",
            "Tharaka",
            "Dhammika",
            "Damith",
            "Ananda",
            "Kapila",
            "Shehan",
            "Dinusha",
            "Gayani",
            "Rajitha",
            "Darshana",
            "Udaya",
            "Nadeesha",
            "Asela",
            "Sajith",
            "Anusha",
            "Ranga",
            "Udara",
            "Upali",
            "Sumith",
            "Pubudu",
            "Eranga",
            "Nihal",
            "Mahinda",
            "Ishara",
            "Susantha",
            "Shantha",
            "Sanath",
            "Sumudu",
            "Sandun",
            "Sujeewa",
            "Kanishka",
            "Danushka",
            "Amal",
            "Lakmal",
            "Thanuja",
            "Ashan",
            "Chathurika",
            "Viraj",
            "Nadeeka",
            "Dimuthu",
            "Kosala",
            "Ravindra",
            "Athula",
            "Niroshan",
            "Asoka",
            "Shanika",
            "Anushka",
            "Palitha",
            "Shanaka",
            "Hemantha",
            "Akila",
            "Chathuranga",
            "Shashika",
            "Bandula",
            "Uditha",
            "Jude",
            "Sisira",
            "Namal",
            "Iresha",//Female
            "Waruni",
            "Ishani",
            "Lakshani",
            "Kushani",
            "Sudath",
            "Sujani",
            "Nilanthika",
            "Rukshani",
            "Harshani",
            "Nishanthika",
            "Nirosha",
            "Gayathri",
            "Hirani",
            "Dilani",
            "Saheni",
            "Sewmini",
            "Inoka",
            "Chaturika",
            "Rameshi",
            "Yohani",
            "Charitha",
            "Rohani",
            "Kumudu",
            "Malki",};
        String[] surnames = {
            "Perera",
            "Fernando",
            "de Silva",
            "Bandara",
            "Kumara",
            "Dissanayake",
            "Mohamed",
            "Gamage",
            "Liyanage",
            "Jayasinghe",
            "Ranasinghe",
            "Herath",
            "Weerasinghe",
            "Peiris",
            "Rathnayake",
            "Wickramasinghe",
            "Wijesinghe",
            "Hettiarachchi",
            "Nanayakkara",
            "Ahamed",
            "Rajapaksha",
            "Mendis",
            "Pathirana",
            "Ekanayake",
            "Gunasekara",
            "Dias",
            "Sampath",
            "Amarasinghe",
            "Ratnayake",
            "Chathuranga",
            "Senanayake",
            "Samarasinghe",
            "Lakmal",
            "Munasinghe",
            "Rodrigo",
            "Seneviratne",
            "Rathnayaka",
            "Edirisinghe",
            "Jayawardena",
            "Fonseka",
            "Sanjeewa",
            "Gunawardana",
            "Prasad",
            "Gunawardena",
            "Karunaratne",
            "Jayaweera",
            "Jayasekara",
            "Ranaweera",
            "Jayawardana",
            "Jayasuriya",
            "Madusanka",
            "Alwis",
            "Rajapakse",
            "Karunarathna",
            "Dissanayaka",
            "Jayakody",
            "Samarakoon",
            "Kariyawasam",
            "Cooray",
            "Karunarathne",
            "Kumari",
            "Abeysinghe",
            "Rupasinghe",
            "Sandaruwan",
            "Weerakoon",
            "Jayalath",
            "Gunasekera",
            "de Alwis",
            "Madushanka",
            "Jayasundara",
            "Tennakoon",
            "Vithanage",
            "Weerasekara",
            "Subasinghe",
            "Kumarasinghe",
            "Hewage",
            "Gunarathna",
            "Gunaratne",
            "Prasanna",
            "Samaraweera",
            "Athukorala",
            "Maduranga",
            "Wijeratne",
            "Wijekoon",
            "Gunathilaka",
            "Hussain",
            "Pushpakumara",
            "Priyadarshana",
            "Samaranayake",
            "Jayathilaka",
            "Lanka",
            "Siriwardana",
            "Gunathilake",
            "Dassanayake",
            "Senevirathne",
            "Pradeep",
            "Mohammed",
            "Yapa",
            "Priyankara",
            "Wijesekara",
            "Desilva",
            "Indika",
            "Attanayake",
            "Farook",
            "Ranathunga",
            "Basnayake",
            "Senaratne",
            "Withanage",
            "Abdul",
            "Madushan",
            "Nishantha",
            "Mohideen",
            "Chamara",
            "Wijerathne",
            "Sri",
            "Kannangara",
            "Siriwardena",
            "Adikari",
            "Jayarathna",
            "Kodithuwakku",
            "Nuwan",
            "Samee",
            "Senevirath",
            "Dilruks",
            "Priyantha",
            "Wanniarachchi",
            "Wijerathna",
            "Jayathilake",
            "Rajakaruna",
            "Udayanga",
            "Gunarathne",
            "Lakmali",
            "Ranatunga",
            "Abeykoon",
            "Karunanayake",
            "Jayasooriya",
            "Tharanga",
            "Abeywickrama",
            "Guruge",
            "Senarath",
            "Wijesundara",
            "Jayasekera",
            "Balasuriya",
            "Hassan",
            "Samarawickrama",
            "Weerakkody",
            "Chandrasiri",
            "Marasinghe",
            "Dilshan",
            "Kuruppu",
            "Priyadarshani",
            "Atapattu",
            "Madushani",
            "Wijesuriya",
            "Kaluarachchi",
            "Weerasooriya",
            "Wijesooriya",
            "Balasooriya",
            "Kodikara",
            "Roshan",
            "de Zoysa"};
//</editor-fold>
        Connection conn = DBconnect.CONN;
        String[] subGrades = {"A", "B", "C", "D"};
        String[] medm = {"Sinhala", "English", "Tamil"};
        String[] gender = {"Male", "Female"};
        String[] phones = {"0765856334", "0740770104", "0704688479", "0704688477", "0762260862"};
        String[] adress = {"50 Madadeniya,Pujapitiya", "205/2 Kotinkaduwa,Pujapitiya", "40 Warakamura,Matale"};
        String[] guard = {"Father", "Mother", "Uncle", "Aunt", "Orphanages"};
        String[] email = {"adithyawije34@gmail.com", "poornimaygs@gmail.com"};
        System.out.println(Arrays.toString(new File("C:\\Users\\Dell\\Documents\\NetBeansProjects\\StudentManagementSystem\\imgs").list()));
        String[] list = new File("C:\\Users\\Dell\\Documents\\NetBeansProjects\\StudentManagementSystem\\imgs").list();
        
        
    }
}
