package com.Main;

public enum Defaults {
    LookAndFeel,
    MD_ImagePath,
    PD_ImagePath,
    PD_SavePath,
    SS_SelectGrade,
    SS_SelectSubGrade,
    SS_SelectMedium,
    MR_PrintSaveDir,
    System_Password,
    System_UserName,
    System_SecurityQuestion,
    System_SecurityAnswer,
    Character_Seq,
    ReportPrinter_MRS_Title,
    ReportPrinter_MRS_Desc,
    ReportPrinter_MRS_Summery,
    ReportPrinter_MRM_Title,
    ReportPrinter_MRM_Desc,
    ReportPrinter_MRM_Summery,
    ReportPrinter_IDC_Title,
    ReportPrinter_IDC_Desc,
    ReportPrinter_IDC_Summery,
    ReportPrinter_Title,
    ReportPrinter_Desc,
    ReportPrinter_Summery,
    SetEmailSubject_Marks_Report_Single_,
    SetEmailSubject_Marks_Report_Multiple_,
    SetEmailSubject_ID_Card,
    SetEmailSubject_Students_Detailes,
    SetEmailSubject_Caracter_Certificate,
    SetEmailSubject_Leaving_Report,
    SetEmailBody_Marks_Report_Single_,
    SetEmailBody_Marks_Report_Multiple_,
    SetEmailBody_ID_Card,
    SetEmailBody_Students_Detailes,
    SetEmailBody_Caracter_Certificate,
    SetEmailBody_Leaving_Report, BINID,
}
